name: CI

on:
  push:
    branches:
      - main
  pull_request:

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  swift-test:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v6

      - name: Show Swift Version
        run: swift --version

      - name: Build
        run: swift build

      - name: Test
        run: swift test
